// Einen Arzt mittels PUT aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Content-Type: application/json
ALPN: h2

< data/arzt-1-put.json

###

// Einen nicht-vorhandenen Arzt mittels PUT aktualisieren: 404
PUT {{baseUrl}}/api/f0000000-0000-0000-0000-000000000001
Content-Type: application/json
ALPN: h2

< data/arzt-1-put.json


###

// Einen Arzt mittels PUT aktualisieren: Email existiert 400
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Content-Type: application/json
ALPN: h2

< data/arzt-1-put-email-exists.json

###

// Einen Arzt mit fehlerhaften Werten mittels PUT auf deutsch aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Content-Type: application/json
Accept-Language: de
ALPN: h2

< data/arzt-1-put-invalid.json

###

// Einen Arzt mit fehlerhaften Werten mittels PUT auf englisch (= default) aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Content-Type: application/json
ALPN: h2

< data/arzt-1-put-invalid.json
